### ISSUE TITLE
Loading from URL?

### ISSUE THREAD

**Issue by SRandazzo** [eVisit/react-native-dynamic-fonts#7]
Hi 👋
Thanks for this great library, i've enjoyed looking through the source so far.

I was wondering if you had any recommendations for remotely loading fonts via http and using them with this library?

I know there are some limitations around Blob and File in ReactNative. I've seen a few solutions posted utilizing [react-native-fetch-block](https://github.com/wkh237/react-native-fetch-blob)
Specifically this recommendation here: https://stackoverflow.com/a/39036374/287814

Thanks again!

**Comment by th317erd** [comment]
Hey there @SRandazzo, thanks for the feedback and question! `react-native-dynamic-fonts` requires a base64 encoded binary font be be provided to the loader functions... [react-native-fetch-blob](https://github.com/wkh237/react-native-fetch-blob) is a great library, but is mostly used when you have raw binary files you need to fetch. If the remote fonts you are loading are raw binary, then I would recommend using a library like [react-native-fetch-blob](https://github.com/wkh237/react-native-fetch-blob) (there is also react-native-fs... but I prefer fetch-blob myself) to load the binary font data and encode using a library like [base-64](https://www.npmjs.com/package/base-64) (`atob`, `btoa` do not work on RN because the JS engine used for RN doesn't support them natively) before passing off to `react-native-dynamic-fonts`. If your remote fonts are controlled by you and can be based64 encoded beforehand this would save processing power for each client, and then I would recommend just sticking with react-natives vanilla `fetch` to fetch the already base64 encoded font. So it depends on your setup. I like fetching remote fonts as a feature of this library list though. I will put that on my "TODO" list. :)

**Comment by SRandazzo** [comment]
Thanks! I appreciate the response and guidance

Base64 on the server sounds reasonable, given the savings in processing power once it reaches the client.

If i come across anything else down this path I will update the issue, but for now you've been very helpful and answered my question. I will close this issue out,  Thanks again!
